title: <p align="center"> Salma Elhassa </p>

logo: "/images/logo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.https://www.linkedin.com/in/salma-elhassa-1761b418a/">LinkedIn</a> |
  <a href="https://github.com/salmaelhassa">GitHub</a>
  </p>
  
  <p align="justify">
 <br> I am pursing MS degree in Biomedical Engineering at Fu Foundation School of Engineering and Applied Science, Columbia University.<br>
 <br> I am interested in optimizing neurostimulation and modulation devices to treat neurological disorders.<br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics:  # Google Analytics tracking ID
