title: <p align="center"> Salma Elhassa </p>

logo: "/images/logo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/salma-elhassa-1761b418a/">LinkedIn</a> |
  <a href="https://github.com/salmaelhassa">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Fu Foundation School of Engineering and Applied Science, Columbia University.
  <br><br>
  I am currently interested in advancing and optimizing neuromodulation and stimulation devices to treat neurological disorders.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics_tracking_id: "G-69DGYXN434"


